### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by jakeoid**
Reverts beautiful-discord-community/resources#52

### CODE REVIEW

**Comment by jakeoid** [comment]
@Nerdietony Can you upload the image to a more reliable server? I merged your PR but noticed the image didn't resolve.

**Comment by TheBITLINK** [comment]
I don't think it's necessary in this case, as this is more of a "copy paste" type snippet, most people would want to put their custom pictures anyway

**Comment by Nerdietony** [comment]
^*

**Comment by zet4** [comment]
If it becomes a problem we can always fix it later, for now its fine.

**Pull request closed without merging**
