### PR TITLE
..?

### PR DESCRIPTION
**Pull request by LewisTehMinerz**
i didn't touch the thing, but for some reason the repo test failed...? apparently the css was incorrect, but it's valid.

Please check if what you want to add to `beautiful-discord-community/resources` list meets [quality standards](https://github.com/beautiful-discord-community/resources/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: 
- embed url: 

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [ ] I know that this package was not listed before
- [x] I have added @import compatible link (ex. [rawgit.com](https://rawgit.com)) to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/beautiful-discord-community/resources/blob/master/CONTRIBUTING.md#contribution-guidelines).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by jakeoid** [comment]
Still failing the test, sorry 😓 , I can't accept the PR till it passes. 

*(no like literally, I cant, the button is greyed out)*

**Comment by zet4** [comment]
lul

**Comment by TheBITLINK** [comment]
Zeta fix the build 👀

**Comment by TheBITLINK** [comment]
No wait the CSS is legit broken
image

image

**Comment by jakeoid** [comment]
Apparently..

```css
   content:"	";
```

**Comment by TriggerRimfire** [comment]
yess

**Comment by LewisTehMinerz** [comment]
Thank you! For some reason the script thinks it's invalid.

**Comment by LewisTehMinerz** [comment]
Is there a way to make the check "not required?"

**Comment by TheBITLINK** [comment]
fix ur shite

**Comment by TriggerRimfire** [comment]
this is a travesty

**Comment by LewisTehMinerz** [comment]
I can't fix it, @TheBITLINK. It's something strange with the test, thinking that a quote is unclosed.

**Comment by jakeoid** [comment]
If we accept with a check on this future PRs will fail on it

**Comment by LewisTehMinerz** [comment]
I don't know, you'll have to fix it.

**Comment by TheBITLINK** [comment]
@LewisTehMinerz can't you just remove whatever symbol you used here?
```
content:"	";
```

Or just use multiple spaces, idk

**Comment by zet4** [comment]
This has dragged on for longer then I would've liked it, please open a PR when you fix the issue.

**Pull request closed without merging**
