### PR TITLE
Updated info to my theme

### PR DESCRIPTION
**Pull request by AlexFlipnote**
Please check if what you want to add to `beautiful-discord-community/resources` list meets [quality standards](https://github.com/beautiful-discord-community/resources/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: 
- embed url: 

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added @import compatible link (ex. [rawgit.com](https://rawgit.com)) to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/beautiful-discord-community/resources/blob/master/CONTRIBUTING.md#contribution-guidelines).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by jakeoid** [comment]
Would've merged but you didn't tick the boxes, smh.

**Comment by TheBITLINK** [comment]
@zet4 fix build 👀

**Comment by AlexFlipnote** [comment]
ticked the boxes now..

**Comment by jakeoid** [comment]
https://this.is-a.dog/af7c9c.png
🤔

**Comment by jakeoid** [comment]
https://this.is-a.dog/f789b0.png

🙃

**Comment by AlexFlipnote** [comment]
It's not my theme that has an error .-.
Lewis' theme is.....

Also, I have not listed this before

**Comment by jakeoid** [comment]
@LewisTehMinerz Your resource was breaking the PR, i've left a copy of it on hastebin here, 

https://hastebin.com/oreyefutal.md

Can you please resubmit the PR with a fixed version please! 

Thanks!

**Comment by LewisTehMinerz** [comment]
@jakeoid i don't understand why there was an issue. i didn't edit the theme at all.

**Pull request merged**
